name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest


    # NOTE: checkout and setup-go are both left at v5, with v6 available, to see if dependabot config works.
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'analyzer/go.mod'
          cache-dependency-path: "**/*.sum"
      - name: Install dependencies
        working-directory: ./analyzer
        run: go get .
      - name: Build
        working-directory: ./analyzer
        run: go build -v ./...
      - name: Test with the Go CLI
        working-directory: ./analyzer
        run: go test ./...
